chore: enable typescript
mazedesignhq/maze-serverless-starter pull request #7
Opened 2020-08-12 12:04 UTC by gasp

enable developers to use typescript for new services

2020-08-12 12:11 UTC, tpombeiro87 approved these changes
👏

2020-08-12 12:27 UTC, gasp commented
inspired by
* maze-api migrate to serverless https://github.com/mazedesignhq/maze-api/commit/530da4ce452219209d7945882a12de316cfa8bae
* babel + ts PR https://github.com/postlight/serverless-babel-starter/pull/42

2020-08-17 11:49 UTC, tgroutars requested changes

2020-08-17 11:49 UTC, tgroutars commented on package.json
> +    "lint": "tslint -c tslint.json --fix './src/**/*.ts' && eslint src --ext js --no-ignore --fix",
Please don't use `tslint` as it's being shut down in favor of `eslint`

2020-08-17 11:49 UTC, tgroutars commented on jest.config.js
> +    '^.+\\.tsx?$': 'ts-jest',
`jest` supports TypeScript via babel so we shouldn't need `ts-jest`

2020-08-28 08:39 UTC, tgroutars approved these changes
🙌

2020-08-28 09:23 UTC, merged